// app/api/report/manager1/route.ts
import { NextResponse } from 'next/server';

export async function GET() {
  const dummyData = {
    title: '매니저1 리포트',
    author: 'manager1',
    date: '2025-07-03',
    fileName: 'report-manager1',
    viewCount: 100,
    totalCount: 200,
    anomalyCount: 23,
    normalCount: 177,
    content: [
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      ' EPC 001: 이상 이동 감지',
      ' EPC 002: 시공간 점프',
      ' EPC 003: EPC 위조 의심',
      
    ]
  };

  return NextResponse.json(dummyData);
}
