import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import { AuthProvider } from "@/context/AuthContext";
import "mapbox-gl/dist/mapbox-gl.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="antialiased">
        <AuthProvider><ClientLayout>{children}</ClientLayout></AuthProvider>
      </body>
    </html>
  );
}
